import { useMemo, useState } from 'react'
import { engagementMessage, renderMatchShareCard, SHARE_DIMENSIONS, suggestedHashtags, type ShareFormat, type ShareMatch } from '../../lib/matchShare'
import './ShareMatchBuilder.css'

export default function ShareMatchBuilder({ match }: { match: ShareMatch }) {
  const [format, setFormat] = useState<ShareFormat>('story'); const [caption, setCaption] = useState(''); const [hashtags, setHashtags] = useState(suggestedHashtags(match).join(' ')); const [status, setStatus] = useState<string | null>(null); const [image, setImage] = useState<HTMLImageElement | null>(null)
  const dimensions = SHARE_DIMENSIONS[format]; const previewStyle = useMemo(() => ({ aspectRatio: `${dimensions.width}/${dimensions.height}` }), [dimensions])
  const loadPhoto = (file?: File) => { if (!file) return; const url = URL.createObjectURL(file); const loaded = new Image(); loaded.onload = () => { setImage(loaded); URL.revokeObjectURL(url) }; loaded.src = url }
  const exportCard = async (share: boolean) => { setStatus('Generating PNG…'); try { const blob = await renderMatchShareCard(match, format, { caption, hashtags, image }); const file = new File([blob], `playpanda-${match.result.toLowerCase()}-${format}.png`, { type: 'image/png' }); if (share && navigator.share && (!navigator.canShare || navigator.canShare({ files: [file] }))) await navigator.share({ title: 'My PlayPanda match', files: [file] }); else { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = file.name; link.click(); URL.revokeObjectURL(url) } setStatus('Share card ready.') } catch (error) { setStatus(error instanceof Error ? error.message : 'Export failed. Try again.') } }
  return <section className="ShareMatchBuilder"><div className="ShareMatchBuilder-preview" style={previewStyle}><div><strong>PLAYPANDA</strong><em>{match.result}</em><b>{match.score}</b><span>{match.sport}</span><small>{match.player} vs {match.opponent}</small><small>{engagementMessage(match)}</small></div></div><div className="ShareMatchBuilder-form"><p className="ShareMatchBuilder-kicker">SHARE YOUR MATCH</p><h1>Build a match story</h1><p className="ShareMatchBuilder-verified">✓ {match.verified ? 'Verified Match' : 'Match not verified'}</p><label>Game photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event => loadPhoto(event.target.files?.[0])} /></label><label>Caption<textarea value={caption} onChange={event => setCaption(event.target.value)} placeholder="What happened in this match?" maxLength={280} /></label><label>Hashtags<input value={hashtags} onChange={event => setHashtags(event.target.value)} /></label><label>Share format<select value={format} onChange={event => setFormat(event.target.value as ShareFormat)}>{Object.entries(SHARE_DIMENSIONS).map(([key, option]) => <option key={key} value={key}>{option.label}</option>)}</select></label><div className="ShareMatchBuilder-actions"><button type="button" disabled={!match.verified} onClick={() => exportCard(false)}>Download PNG</button><button type="button" disabled={!match.verified} onClick={() => exportCard(true)}>Share</button></div>{status && <p role="status">{status}</p>}</div></section>
}
