import { useMemo, useState } from 'react'
import { engagementMessage, renderShareCardPng, SHARE_DIMENSIONS, shareFileName, suggestedHashtags, type ShareFormat, type ShareMatch } from '../../lib/matchShare'
import './ShareMatchBuilder.css'

export default function ShareMatchBuilder({ match }: { match: ShareMatch }) {
  const [format, setFormat] = useState<ShareFormat>('story'); const [caption, setCaption] = useState(''); const [hashtags, setHashtags] = useState(suggestedHashtags(match).join(' ')); const [status, setStatus] = useState<string | null>(null); const [image, setImage] = useState<HTMLImageElement | null>(null)
  const dimensions = SHARE_DIMENSIONS[format]; const previewStyle = useMemo(() => ({ aspectRatio: `${dimensions.width}/${dimensions.height}`, backgroundImage: image ? `linear-gradient(145deg, rgba(8,13,11,.25), rgba(8,13,11,.88)), url(${image.src})` : undefined }), [dimensions, image])
  const loadPhoto = (file?: File) => { if (!file) return; const url = URL.createObjectURL(file); const loaded = new Image(); loaded.onload = () => { setImage(loaded); URL.revokeObjectURL(url) }; loaded.src = url }
  const exportCard = async (share: boolean) => { setStatus('Generating PNG…'); try { const blob = await renderShareCardPng(match, format, { caption, hashtags: hashtags.split(/\s+/).filter(Boolean), showStats: true, image }); const file = new File([blob], shareFileName(match, format), { type: 'image/png' }); if (share && navigator.share && (!navigator.canShare || navigator.canShare({ files: [file] }))) await navigator.share({ title: 'My PlayPanda match', files: [file] }); else { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = file.name; link.click(); URL.revokeObjectURL(url) } setStatus('Share card ready.') } catch (error) { setStatus(error instanceof Error ? error.message : 'Export failed. Try again.') } }
  return <section className="ShareMatchBuilder"><div className="ShareMatchBuilder-preview-wrap"><div className="ShareMatchBuilder-preview-label">LIVE PREVIEW <span>{dimensions.label}</span></div><div className="ShareMatchBuilder-preview" style={previewStyle}><div><strong>PLAYPANDA</strong><em>{match.result}</em><b>{match.score}</b><span>{match.sport}{match.format ? ` · ${match.format}` : ''}</span><small>{match.player} <i>vs</i> {match.opponent}</small><small>{engagementMessage(match)}</small></div></div></div><div className="ShareMatchBuilder-form"><p className="ShareMatchBuilder-kicker">SHARE YOUR MATCH</p><h1>Build a match story</h1><p className="ShareMatchBuilder-helper">Your match facts are locked to the official result. Personalize the moment around them.</p><p className="ShareMatchBuilder-verified">✓ {match.verification === 'confirmed' ? 'Confirmed Match' : 'Match not verified'}</p><div className="ShareMatchBuilder-detail"><span>Official result</span><strong>{match.result} · {match.score}</strong><small>{match.sport} · {new Date(match.playedAt).toLocaleDateString()}</small></div><label>Game photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event => loadPhoto(event.target.files?.[0])} /><small>JPG, PNG or WEBP. Your original file is not changed.</small></label><label>Caption<textarea value={caption} onChange={event => setCaption(event.target.value)} placeholder="What happened in this match?" maxLength={280} /></label><label>Hashtags<input value={hashtags} onChange={event => setHashtags(event.target.value)} /></label><fieldset><legend>Share format</legend><div className="ShareMatchBuilder-format-options">{Object.entries(SHARE_DIMENSIONS).map(([key, option]) => <button type="button" key={key} className={format === key ? 'is-active' : ''} onClick={() => setFormat(key as ShareFormat)}>{option.label}<small>{option.hint}</small></button>)}</div></fieldset><div className="ShareMatchBuilder-actions"><button type="button" className="is-primary" disabled={match.verification !== 'confirmed'} onClick={() => exportCard(false)}>Download PNG</button><button type="button" className="is-secondary" disabled={match.verification !== 'confirmed'} onClick={() => exportCard(true)}>Share</button></div>{status && <p role="status" className="ShareMatchBuilder-status">{status}</p>}</div></section>
}
