import { useState } from 'react'
import { createCourtKey, isCourtKey, normalizeCourtKey, type CourtRole } from '../lib/courts'
import './CourtsPage.css'

export default function CourtsPage() {
  const [key, setKey] = useState(''); const [createdKey, setCreatedKey] = useState<string | null>(null); const [role, setRole] = useState<CourtRole>('player'); const [notice, setNotice] = useState<string | null>(null)
  const create = () => { const generated = createCourtKey(); setCreatedKey(generated); setNotice('Court created. Share this CourtKey only with the people allowed to enter.') }
  const join = () => { const normalized = normalizeCourtKey(key); if (!isCourtKey(normalized)) { setNotice('Enter a valid CourtKey, for example ABCD-2345.'); return } setNotice(`Join request ready for ${normalized} as ${role}. The server must verify this key and role before entry.`) }
  return <main className="CourtsPage"><header><p className="CourtsPage-kicker">PRIVATE PLAY SPACE</p><h1>Courts</h1><p>Create a private court for your tournament or enter a CourtKey shared by the organizer, players, scorer, or spectators.</p></header><section className="CourtsPage-grid"><article><span className="CourtsPage-label">CREATE A COURT</span><h2>Open your tournament court</h2><p>The system generates a unique CourtKey. Share it only with approved participants.</p><button type="button" className="CourtsPage-primary" onClick={create}>Create court</button>{createdKey && <div className="CourtsPage-key"><small>YOUR COURTKEY</small><strong>{createdKey}</strong><button type="button" onClick={() => navigator.clipboard?.writeText(createdKey)}>Copy key</button></div>}</article><article><span className="CourtsPage-label">ENTER A COURT</span><h2>Join with CourtKey</h2><label>CourtKey<input value={key} onChange={event => setKey(event.target.value)} placeholder="ABCD-2345" maxLength={9} /></label><fieldset><legend>How are you entering?</legend>{(['player', 'scorer', 'spectator'] as CourtRole[]).map(option => <label key={option}><input type="radio" name="court-role" checked={role === option} onChange={() => setRole(option)} />{option[0].toUpperCase() + option.slice(1)}</label>)}</fieldset><button type="button" className="CourtsPage-primary" onClick={join}>Enter court</button></article></section>{notice && <p className="CourtsPage-notice" role="status">{notice}</p>}<aside className="CourtsPage-security"><strong>Access control</strong><span>CourtKey is only an invite key. The server still checks tournament membership and whether the selected role is allowed. Never trust a browser-selected scorer role.</span></aside></main>
}
